import assert from "node:assert/strict";
import test from "node:test";
import { exportDesignMd } from "../dist/index.js";
import { serializeDesignSystemCss } from "../dist/core/export/css.js";
import type { DesignSystem, ResolvedToken, SourceSpan } from "../dist/index.js";
import {
  replaceColorsYaml,
  replaceTypographyYaml,
  replaceShapesYaml,
  validDesignMd,
  withElevationYaml,
  withMetadata,
  withMotionYaml,
} from "./fixtures.ts";

type DiagnosticSeverity = "error" | "warning";
type DiagnosticResult = {
  diagnostics: Array<{ rule: string; severity: DiagnosticSeverity }>;
};
type TokenValue = ResolvedToken["value"];

const span: SourceSpan = {
  start: { line: 1, column: 1, offset: 0 },
  end: { line: 1, column: 1, offset: 0 },
};

function exportCss(source: string, format: "css" | "css-tailwind" = "css") {
  return exportDesignMd(source, { filePath: "DESIGN.md", format });
}

function yaml(...lines: string[]): string {
  return lines.join("\n");
}

function assertDiagnostic(result: DiagnosticResult, rule: string, severity: DiagnosticSeverity) {
  assert.ok(
    result.diagnostics.some(
      (diagnostic) => diagnostic.rule === rule && diagnostic.severity === severity,
    ),
    `Expected ${severity} diagnostic '${rule}'. Got: ${result.diagnostics.map((diagnostic) => diagnostic.rule).join(", ")}`,
  );
}

function token(path: string, value: TokenValue): ResolvedToken {
  const group = path.split(".")[0];
  assert.ok(group !== undefined);

  return {
    path,
    group: group as ResolvedToken["group"],
    value,
    references: [],
    span,
  };
}

function designSystem(tokens: ResolvedToken[], themes: string[] = []): DesignSystem {
  return {
    name: "Test",
    themes,
    tokens: new Map(tokens.map((item) => [item.path, item])),
    containerPaths: new Set(),
    tokenCountByGroup: {},
  };
}

test("css export emits root variables and converts embedded references", () => {
  const result = exportCss(
    withElevationYaml(
      yaml("shadow:", '  focus-ring: "0 0 0 3px {colors.primary}"', "zIndex:", "  modal: 1000"),
    ),
  );

  assert.equal(result.valid, true);
  const output = result.output ?? "";
  assert.match(output, /Generated by designmd from DESIGN\.md/);
  assert.match(output, /:root \{/);
  assert.match(output, /--color-primary: #1A1C1E;/);
  assert.match(output, /--font-sans: Inter, system-ui, sans-serif;/);
  assert.match(output, /--shadow-focus-ring: 0 0 0 3px var\(--color-primary\);/);
  assert.match(output, /--z-index-modal: 1000;/);
});

test("css-tailwind export emits static theme variables and skips non-tailwind namespaces", () => {
  const source = withMotionYaml(
    yaml(
      "duration:",
      '  slow: "300ms"',
      "easing:",
      '  standard: "ease-out"',
      "reducedMotion:",
      '  slow: "100ms"',
    ),
    withElevationYaml(
      yaml("shadow:", '  md: "0 8px 24px rgb(0 0 0 / 0.12)"', "zIndex:", "  modal: 1000"),
      replaceShapesYaml(
        yaml(
          "radius:",
          "  none: 0",
          '  sm: "0.25rem"',
          '  md: "0.5rem"',
          '  full: "9999px"',
          "borderWidth:",
          '  thin: "1px"',
        ),
      ),
    ),
  );
  const result = exportCss(source, "css-tailwind");

  assert.equal(result.valid, true);
  const output = result.output ?? "";
  assert.match(output, /@theme static \{/);
  assert.match(output, /--color-primary: #1A1C1E;/);
  assert.match(output, /--shadow-md: 0 8px 24px rgb\(0 0 0 \/ 0\.12\);/);
  assert.match(output, /--ease-standard: ease-out;/);
  assert.doesNotMatch(output, /--z-index-modal/);
  assert.doesNotMatch(output, /--duration-slow/);
  assert.doesNotMatch(output, /--border-width-thin/);
});

test("css export emits primitive typography ramps and text references", () => {
  const result = exportCss(
    replaceTypographyYaml(
      yaml(
        "fontFamily:",
        '  sans: "Inter"',
        'baseFontSize: "16px"',
        "fontSize:",
        '  "1": "0.875rem"',
        "fontWeight:",
        '  "1": 400',
        "lineHeight:",
        '  "1": 1.5',
        "letterSpacing:",
        '  "1": "0em"',
        "text:",
        "  body:",
        '    fontFamily: "{typography.fontFamily.sans}"',
        '    fontSize: "{typography.fontSize.1}"',
        '    fontWeight: "{typography.fontWeight.1}"',
        '    lineHeight: "{typography.lineHeight.1}"',
        '    letterSpacing: "{typography.letterSpacing.1}"',
      ),
    ),
  );

  assert.equal(result.valid, true);
  const output = result.output ?? "";
  assert.match(output, /--text-1: 0\.875rem;/);
  assert.match(output, /--font-weight-1: 400;/);
  assert.match(output, /--leading-1: 1\.5;/);
  assert.match(output, /--tracking-1: 0em;/);
  assert.match(output, /--text-body: var\(--text-1\);/);
  assert.match(output, /--font-weight-body: var\(--font-weight-1\);/);
  assert.match(output, /--leading-body: var\(--leading-1\);/);
  assert.match(output, /--tracking-body: var\(--tracking-1\);/);
});

test("css export emits default theme values at root and other themes under data-theme selectors", () => {
  const source = withMetadata(
    yaml("themes:", '  - "light"', '  - "dark"', 'defaultTheme: "dark"'),
    replaceColorsYaml(
      yaml(
        'primary: "{colors.surface}"',
        "surface:",
        '  light: "#ffffff"',
        '  dark: "#111111"',
        "on-surface:",
        '  light: "#111111"',
        '  dark: "#ffffff"',
      ),
    ),
  );
  const result = exportCss(source);

  assert.equal(result.valid, true);
  const output = result.output ?? "";
  assert.match(output, /:root \{[\s\S]*--color-primary: var\(--color-surface\);/);
  assert.match(output, /:root \{[\s\S]*--color-surface: #111111;/);
  assert.match(output, /\[data-theme="light"\] \{[\s\S]*--color-surface: #ffffff;/);
});

test("export blocks errors while allowing warnings", () => {
  const invalid = exportCss(
    replaceColorsYaml(yaml('primary: "red"', 'surface: "#ffffff"', 'on-surface: "#000000"')),
  );
  assert.equal(invalid.valid, false);
  assert.equal(invalid.output, undefined);
  assertDiagnostic(invalid, "invalid-color", "error");

  const warningOnly = exportCss(
    validDesignMd.replace(
      "Acme uses calm surfaces and clear hierarchy.",
      "Acme uses calm surfaces and clear hierarchy. Avoid 16px in prose.",
    ),
  );
  assert.equal(warningOnly.valid, true);
  assert.match(warningOnly.output ?? "", /:root \{/);
  assertDiagnostic(warningOnly, "hard-coded-prose-value", "warning");
});

test("export fails on CSS variable collisions after slugging", () => {
  const result = exportCss(
    replaceColorsYaml(
      yaml(
        'primary-color: "#000000"',
        'primaryColor: "#111111"',
        'surface: "#ffffff"',
        'on-surface: "#000000"',
      ),
    ),
  );

  assert.equal(result.valid, false);
  assert.equal(result.output, undefined);
  assertDiagnostic(result, "css-variable-collision", "error");
});

test("CSS serializer reports unexportable references and missing theme values", () => {
  const unexportable = serializeDesignSystemCss(
    designSystem([
      token("colors.primary", "{motion.duration.fast}"),
      token("motion.duration.fast", "150ms"),
    ]),
    { format: "css-tailwind" },
  );

  assert.equal(unexportable.output, undefined);
  assertDiagnostic(unexportable, "unexportable-reference", "error");

  const missingRootTheme = serializeDesignSystemCss(
    designSystem([token("colors.primary", { light: "#ffffff" })]),
    { format: "css" },
  );

  assert.equal(missingRootTheme.output, undefined);
  assertDiagnostic(missingRootTheme, "missing-theme-value", "error");

  const missingThemeValue = serializeDesignSystemCss(
    designSystem([token("colors.primary", { light: "#ffffff" })], ["light", "dark"]),
    { format: "css" },
  );

  assert.equal(missingThemeValue.output, undefined);
  assertDiagnostic(missingThemeValue, "missing-theme-value", "error");
});

test("CSS serializer escapes theme selectors and uses default source name", () => {
  const result = serializeDesignSystemCss(
    designSystem(
      [token("colors.primary", { light: "#ffffff", 'dark"\\\nmode': "#000000" })],
      ["light", 'dark"\\\nmode'],
    ),
    { format: "css" },
  );

  assert.equal(result.diagnostics.length, 0);
  const output = result.output ?? "";
  assert.match(output, /Generated by designmd from DESIGN\.md/);
  assert.match(output, /\[data-theme="dark\\"\\\\\\a mode"\]/);
});
