import assert from "node:assert/strict";
import test from "node:test";
import { exportDesignMd } from "../dist/index.js";
import {
  replaceColorsYaml,
  replaceShapesYaml,
  validDesignMd,
  withElevationYaml,
  withMetadata,
  withMotionYaml,
} from "./fixtures.mjs";

function exportCss(source, format = "css") {
  return exportDesignMd(source, { filePath: "DESIGN.md", format });
}

function yaml(...lines) {
  return lines.join("\n");
}

function assertDiagnostic(result, rule, severity) {
  assert.ok(
    result.diagnostics.some(
      (diagnostic) => diagnostic.rule === rule && diagnostic.severity === severity,
    ),
    `Expected ${severity} diagnostic '${rule}'. Got: ${result.diagnostics.map((diagnostic) => diagnostic.rule).join(", ")}`,
  );
}

test("css export emits root variables and converts embedded references", () => {
  const result = exportCss(
    withElevationYaml(
      yaml("shadow:", '  focus-ring: "0 0 0 3px {colors.primary}"', "zIndex:", "  modal: 1000"),
    ),
  );

  assert.equal(result.valid, true);
  assert.match(result.output, /Generated by designmd from DESIGN\.md/);
  assert.match(result.output, /:root \{/);
  assert.match(result.output, /--color-primary: #1A1C1E;/);
  assert.match(result.output, /--font-sans: Inter, system-ui, sans-serif;/);
  assert.match(result.output, /--shadow-focus-ring: 0 0 0 3px var\(--color-primary\);/);
  assert.match(result.output, /--z-index-modal: 1000;/);
});

test("css-tailwind export emits static theme variables and skips non-tailwind namespaces", () => {
  const source = withMotionYaml(
    yaml(
      "duration:",
      '  slow: "300ms"',
      "easing:",
      '  standard: "ease-out"',
      "reducedMotion:",
      '  slow: "100ms"',
    ),
    withElevationYaml(
      yaml("shadow:", '  md: "0 8px 24px rgb(0 0 0 / 0.12)"', "zIndex:", "  modal: 1000"),
      replaceShapesYaml(
        yaml(
          "radius:",
          "  none: 0",
          '  sm: "0.25rem"',
          '  md: "0.5rem"',
          '  full: "9999px"',
          "borderWidth:",
          '  thin: "1px"',
        ),
      ),
    ),
  );
  const result = exportCss(source, "css-tailwind");

  assert.equal(result.valid, true);
  assert.match(result.output, /@theme static \{/);
  assert.match(result.output, /--color-primary: #1A1C1E;/);
  assert.match(result.output, /--shadow-md: 0 8px 24px rgb\(0 0 0 \/ 0\.12\);/);
  assert.match(result.output, /--ease-standard: ease-out;/);
  assert.doesNotMatch(result.output, /--z-index-modal/);
  assert.doesNotMatch(result.output, /--duration-slow/);
  assert.doesNotMatch(result.output, /--border-width-thin/);
});

test("css export emits default theme values at root and other themes under data-theme selectors", () => {
  const source = withMetadata(
    yaml("themes:", '  - "light"', '  - "dark"', 'defaultTheme: "dark"'),
    replaceColorsYaml(
      yaml(
        'primary: "{colors.surface}"',
        "surface:",
        '  light: "#ffffff"',
        '  dark: "#111111"',
        "on-surface:",
        '  light: "#111111"',
        '  dark: "#ffffff"',
      ),
    ),
  );
  const result = exportCss(source);

  assert.equal(result.valid, true);
  assert.match(result.output, /:root \{[\s\S]*--color-primary: var\(--color-surface\);/);
  assert.match(result.output, /:root \{[\s\S]*--color-surface: #111111;/);
  assert.match(result.output, /\[data-theme="light"\] \{[\s\S]*--color-surface: #ffffff;/);
});

test("export blocks errors while allowing warnings", () => {
  const invalid = exportCss(
    replaceColorsYaml(yaml('primary: "red"', 'surface: "#ffffff"', 'on-surface: "#000000"')),
  );
  assert.equal(invalid.valid, false);
  assert.equal(invalid.output, undefined);
  assertDiagnostic(invalid, "invalid-color", "error");

  const warningOnly = exportCss(
    validDesignMd.replace(
      "Acme uses calm surfaces and clear hierarchy.",
      "Acme uses calm surfaces and clear hierarchy. Avoid 16px in prose.",
    ),
  );
  assert.equal(warningOnly.valid, true);
  assert.match(warningOnly.output, /:root \{/);
  assertDiagnostic(warningOnly, "hard-coded-prose-value", "warning");
});

test("export fails on CSS variable collisions after slugging", () => {
  const result = exportCss(
    replaceColorsYaml(
      yaml(
        'primary-color: "#000000"',
        'primaryColor: "#111111"',
        'surface: "#ffffff"',
        'on-surface: "#000000"',
      ),
    ),
  );

  assert.equal(result.valid, false);
  assert.equal(result.output, undefined);
  assertDiagnostic(result, "css-variable-collision", "error");
});
